// Generate config.js from environment variables at build time.
//
// Vercel runs this via the `buildCommand` in vercel.json. The generated
// file is what browsers actually load. Self-host clones don't run this
// script (no build step locally), so the committed config.js stays empty
// and the app starts in Self-Host mode without auth.
//
// Required env vars on the Vercel project:
//   - API_BASE          Cloud Run service URL (no trailing slash)
//   - SUPABASE_URL      e.g. https://xxx.supabase.co
//   - SUPABASE_ANON_KEY public anon JWT (legacy format)
//
// All three default to empty when unset, so the build never fails — the
// resulting site just won't be able to log in or call the backend.

const fs   = require('fs');
const path = require('path');

const apiBase = (process.env.API_BASE          || '').replace(/\/$/, '');
const supaUrl = (process.env.SUPABASE_URL      || '').replace(/\/$/, '');
const supaKey =  process.env.SUPABASE_ANON_KEY || '';

const target = path.join(__dirname, '..', 'config.js');

const content = `// AUTO-GENERATED by scripts/generate-config.js — do not edit by hand.
// Vercel produces this at build time from env vars. Committed copy has
// empty defaults so Self-Host clones run without a build step.
(function () {
    const host = location.hostname;
    const isLocal = host === 'localhost' || host === '127.0.0.1' || host === '';
    window.API_BASE          = isLocal ? '' : ${JSON.stringify(apiBase)};
    window.SUPABASE_URL      = isLocal ? '' : ${JSON.stringify(supaUrl)};
    window.SUPABASE_ANON_KEY = isLocal ? '' : ${JSON.stringify(supaKey)};
})();
`;

fs.writeFileSync(target, content);
const masked = supaKey ? supaKey.slice(0, 8) + '…(' + supaKey.length + ' chars)' : '(empty)';
console.log(`config.js written: API_BASE=${apiBase || '(empty)'} SUPABASE_URL=${supaUrl || '(empty)'} ANON=${masked}`);
